### ISSUE TITLE
Purpose of "Use Tumblr Theme" checkbox

### ISSUE THREAD

**Issue by rralian** [Automattic/tumblr-theme-garden#48]
What is the purpose of the "use Tumblr Theme" checkbox in the customizer?

![use custom theme](https://d.pr/i/G2r3Ue+)

When I de-select it, nothing seems to happen. And I'm not sure what I would expect to happen. Is this just a carryover from a previous iteration?

**Comment by tommusrhodus** [comment]
> Is this just a carryover from a previous iteration?

Correct, the customizer experience is an area that falls under `UX Polishing`. I appreciate you running through these! This one is an easy solve at least 😄

**Comment by tommusrhodus** [comment]
Closing this as it's solved.
