### ISSUE TITLE
Improve HTML editing experience

### ISSUE THREAD

**Issue by rralian** [Automattic/tumblr-theme-garden#49]
### Description

Can we improve the HTML authoring experience in T3? When I edit HTML in Tumblr I get some fairly robust tooling.

![tumblr editing experience](https://d.pr/i/Lp77Fn+)

First, the sidebar expands a bit to give me more space to work with and I can resize it further to my preference. The code has syntax highlighting and line numbers. And there are a number of features available when clicking the cog menu.

I'm not sure we need all of this. We for sure don't need "theme assets" or "submit theme" for example. And the jump-to and replace options seems like nice-to-haves. But the current state in T3 is just a textarea which is pretty barebones.

![t3 html editing](https://d.pr/i/wOadjD+)

Hopefully we could just copy/paste quite a bit of this.

**Comment by tommusrhodus** [comment]
Agreed, there are improvements we can make here!

**Comment by tommusrhodus** [comment]
HTML editing experience is vastly improved. Closing this issue to reflect this.
