### ISSUE TITLE
Parser is parsing commented tags

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#5]
### Description

HTML Template has /* {BackgroundColor} */

![Image](https://github.com/user-attachments/assets/316de944-dfb7-48a8-8568-3e8efb77252a)

Parser is changing it to hex code:

![Image](https://github.com/user-attachments/assets/977d6b75-8600-49cf-a2f6-cd5b2b98029a)

It should probably ignore commented tags

**Comment by tommusrhodus** [comment]
@aaronjbaptiste I fixed this in a recent PR 😄
