### ISSUE TITLE
Improve Theme Browsing in Customizer

### ISSUE THREAD

**Issue by rralian** [Automattic/tumblr-theme-garden#50]
### Description

The Tumblr theme browsing experience is pretty good when you pick your first theme. But if you want to try out a few themes before making a decision it's not a great experience.

I start here and select a theme.

![theme selector step](https://d.pr/i/oDfsGf+)

This launches the customizer.

![customizer step](https://d.pr/i/ma5aTi+)

Now if I want to try something else, I click the "change" button by the "Active Theme." This takes me to a theme selector view in the customizer.

![theme selector](https://d.pr/i/JeYosR+)

Notice that I have two options here... "Installed Themes" (which is selected) and "WordPress.org Themes." I don't have a way of choosing other Tumblr themes from here.

I would expect to have a "Tumblr Themes" option available on this step. And maybe it should be the default/selected option when coming through this flow.

Currently my only option to select different Tumblr themes is to back up to the Tumblr Themes menu under "Appearance."

**Comment by roccotripaldi** [comment]
As part of this issue, I also want to add a link here:

![Image](https://github.com/user-attachments/assets/f5c5b4d5-9310-4d0a-aa34-4e6739d872e1)
