### ISSUE TITLE
Resolve issues/errors reported by Plugin Check

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#62]
### Description

We should resolve these errors before the plugin is reviewed.

![Image](https://github.com/user-attachments/assets/808855b4-b116-4ca3-93ea-48970bfbe1be)

### Steps to reproduce

1. Install Plugin check plugin
2. Run from Tools > Plugin Check
3. Resolve reported issues

**Comment by tommusrhodus** [comment]
These errors are now resolved.

Note that for translation, your plugin folder slug needs to match the translation key `tumblr-theme-garden`

All other fixable errors are resolved, there's two advisories (Screenshot), neither of these are resolvable.

<img width="1554" alt="Image" src="https://github.com/user-attachments/assets/deceb73a-f4df-4aad-af66-5c10b95eeb60" />
