### ISSUE TITLE
Plugin upload failed checks

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#64]
### Description

1. Plugin upload to wordpress.org was not happy about redvelvet's run-test.sh file, we should remove it and the test folder from the release (see .github/workflows/build-release.yml)

> Error: the plugin contains unexpected files. The following files are not permitted in plugins: run-tests.sh. Please remove them and upload the plugin again.

2. Raised here: https://github.com/Automattic/T3/issues/62, issues with Plugin Check

> Error: The plugin has failed the automated checks. Please correct the listed problems with your plugin and upload it again. You can also use the [Plugin Check Plugin](https://wordpress.org/plugins/plugin-check/) to test your plugin before uploading. If you have any questions about this, please contact [plugins@wordpress.org](mailto:plugins@wordpress.org).
> 
> Results of Automated Plugin Scanning: Fail
> 
> phpunit.xml.dist [ERROR: application_detected](https://en-gb.wordpress.org/plugins/developers/add/): Application files are not permitted.
readme.txt [ERROR: outdated_tested_upto_header](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#readme-header-information): Tested up to: 6.5 < 6.7. The "Tested up to" value in your plugin is not set to the current version of WordPress. This means your plugin will not show up in searches, as we require plugins to be compatible and documented as tested up to the most recent version of WordPress.
tumblr-theme-garden.php [WARNING: textdomain_mismatch](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/): The "Text Domain" header in the plugin file does not match the slug. Found "tumblr3", expected "tumblr-theme-garden".
> The above may contain false-positives. If you believe an error or warning is incorrect or a false-positive, please do not work around it. A reviewer will manually confirm this during the review process.
>
> Note: While the automated plugin scan is based on the Plugin Review Guidelines, it is not a complete review. A successful result from the scan does not guarantee that the plugin will be approved, only that it is sufficient to be reviewed. All submitted plugins are checked manually to ensure they meet security and guideline standards before approval.

### Steps to reproduce

1. Download release zip for 0.1.14
2. Upload to wordpress.org plugin submit (log in to a .org account with your @automattic email as they use the email domain to verify organisation).
3. See errors

**Comment by aaronjbaptiste** [comment]
@tommusrhodus I made a start on issue 1 here https://github.com/Automattic/T3/pull/65

if you could take a look at the Plugin check issues!

**Comment by rtio** [comment]
whoopsie daisy, closed this issue by mistake

**Comment by tommusrhodus** [comment]
@aaronjbaptiste successfully uploaded! Time to close this now :)
