### ISSUE TITLE
Pagination is repeating content with endless scrolling on

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#77]
### Description

1. Enable endless scrolling
2. Not sure if related but I have sticky post (tag a post with sticky)
3. Scroll down
4. Notice the same posts are loaded in (including the sticky post)

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/04ad6c5d-06c3-4695-a428-e64c304c74a7" />
<img width="700" alt="Image" src="https://github.com/user-attachments/assets/98b0a5c3-9673-4f5e-bec7-6f8e144c6b26" />

**Comment by tommusrhodus** [comment]
I think I've got this one figured out!
