### ISSUE TITLE
The Chat post format is the only one that doesn't discard other content

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#78]
### Description

Other post types discard other content, the chat post format keeps the title which feels inconsistent.

<img width="675" alt="Image" src="https://github.com/user-attachments/assets/8e2be66b-8d37-40ab-949c-26c38f7b28b6" />

**Comment by tommusrhodus** [comment]
@aaronjbaptiste The chat post format includes title support in tumblr :)

https://www.tumblr.com/docs/en/custom_themes#chat-posts
