### ISSUE TITLE
beaded theme - accent color defaults to {AccentColor}

### ISSUE THREAD

**Issue by aaronjbaptiste** [Automattic/tumblr-theme-garden#88]
### Description

1. Activate beaded theme
2. Open Color and open the accent color picker
3. It has value {AccentColor}
4. This goes to the correct value when you press "default" button

<img width="284" alt="Image" src="https://github.com/user-attachments/assets/3879e7c1-b250-4c99-9046-8b44b6fa7edc" />

**Comment by tommusrhodus** [comment]
This seems to happen in Rosemary as well

**Comment by tommusrhodus** [comment]
DB values appear as expected, something is going wrong in a step between the DB and the customizer.

**Comment by tommusrhodus** [comment]
This might be related to my method of setting default values in options, I forgot to add sanitizing.
